spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://10.10.15.146:3306/changeable_lane_coordination?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: supconit
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      validation-timeout: 3000
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 120000
      minimum-idle: 10
#  boot:
#    admin:
#      client:
#        url: http://33.94.247.151:9001
#        instance:
#          service-base-url: http://33.94.247.151:9030
  application:
    name: changeable-lane-associdinate
  main:
    allow-bean-definition-overriding: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
# 服务器配置
server:
  port: 9031
# mybatis配置
mybatis:
  # 配置映射类所在包名
  type-aliases-package:
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations: classpath:mapper/*Mapper.xml
  # - mappers/ProductMapper.xml
  # - mappers/ShopMapper.xml
  configuration:
    #延迟加载
    lazy-loading-enabled: true
    # 按需加载
    aggressive-lazy-loading: false
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-load-trigger-methods: "toString()"
  type-handlers-package:

  #log-impl: SLF4J

logging:
  level:
    com.supconit.suptap.*: info
  pattern:
    #console: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%level]:%msg%n"
    #file: "%d{yyyy-MM-dd HH:mm:ss.SSS}[%level]:%msg%n"
    charset: UTF-8
  file:
    path: D:\AlgorithmPlatform\suptap-log\${spring.application.name}

url:
  dataManagementUrl: http://10.10.15.146:9010/api/v1
  effectAssessmentUrl: http://10.10.15.146:9014/api/v1
  selfAdaptiveAlgorithmUrl: http://10.10.15.146:9013/api/v1
  dataProcessUrl: http://10.10.15.146:9012/api/v1
  userOperationUrl: http://10.10.15.146:9016/api/v1
  singleUrl: http://10.10.15.146:1991
  dataExchangeUrl: http://10.10.15.146:9008/api/v1
  algorithmUrl: http://10.10.100.16:1990
  variableLaneUrl: http://10.10.15.146:9021/api/v1
  aiEffectAssessmentUrl: http://10.10.15.146:9024/api/v1
  generalPlatformUrl: http://10.10.77.111:8087
  trafficScreenUrl: http://10.10.77.111:8087

param:
  acss: 200048,200047,200299

  acsId-intersectionId: "{200048: 300014, 200047: 200047,200299: 200299}"
  keyAcsId: 200048,200047

